### ISSUE TITLE
Create README file

### ISSUE THREAD

**Issue by bmar268** [SOFTENG310-VicRoy/310-RondayView#5]
**Describe the documentation improvement**
Creating an initial version of the README file.

**What is the purpose for the change?**
Need to include a description of the project and instructions on how to run it.

**Additional context**
This will most likely NOT be the only alteration of this file.

**Comment by N3v1** [comment]
Hi @bmar268, Hi @SOFTENG310-VicRoy 👋,
I would like to help if it's ok with you.

Thank you kindly 🙏
Best regards
NH
