### ISSUE TITLE
View Events that Friends are Going to

### ISSUE THREAD

**Issue by mhardy88** [SOFTENG310-VicRoy/310-RondayView#65]
**Describe the feature**
A user should be able to view a list of their "friends" and also view which events each of their friends are going to. A user may then be able to select interested on these events.

**Possible implementation(s)**
One possible implementation is a recycler view that displays cardviews that relate to each of a users friends. A user can then select one of their friends and be taken to a page displaying all of the friends liked events.

**Additional context**
Similar to other social medias where you can enter a user's profile and it displays their "timeline" or "posts" except here, we are viewing a users liked events. Check out some other social medias for inspiration!

**Comment by nbel806** [comment]
Blocked by #64
