### ISSUE TITLE
Event Rating and Comments - For Previous and Current events

### ISSUE THREAD

**Issue by mhardy88** [SOFTENG310-VicRoy/310-RondayView#71]
**Describe the feature**
A user should be able to comment on and view comments on upcoming events. A user should also be able to comment on and rate events that have already happened for a period of time.

**Possible implementation(s)**
Possibly in the detailed view of an event, a user should be able to input a comment to the event and view other users comments. They may also be able to view events that they were interested in and happened within an amount of time ago (e.g. 48 hours ago) and still comment and rate them. Possibly a rating out of 5, similar to movies. The event should also have an average rating from users rating of it that will be displayed on the details view (of course, this can only be visible after the event has happened, as you cannot rate an event that has not yet happened.

**Additional context**
Many social media apps allow users to comment on other users media, such as Instagram or Facebook. Check them out for inspiration on the commenting feature! For the rating feature, we were imagining something similar to a movie rating. Check out apps like LetterBoxd for similar rating features!

**Comment by nbel806** [comment]
Blocked by #68

**Comment by tmur647** [comment]
made a start on this by adding the comments

**Comment by tmur647** [comment]
still need to add event rating

**Comment by yxin202** [comment]
> still need to add event rating

I will do that

**Comment by tmur647** [comment]
completed by #123
