### ISSUE TITLE
[A2 FEATURE] changing the interested events button from heart to more intuitive button

### ISSUE THREAD

**Issue by tmur647** [SOFTENG310-VicRoy/310-RondayView#85]
**Describe the feature**
the interested events button instead of a heart should be a more intuitive button so the user knows it is the button that takes them to the interested events page

**Possible implementation(s)**
instead of using a heart button could have a dropdown that when clicked drops down a button that says interested vents

**Additional context**
N/A

**Comment by nbel806** [comment]
Yeah, I think I would prefer to see this in the menu bar eventually as I think that's more intuitive.

**Comment by tmur647** [comment]
makes sense, will add it to the navbar
